# 1
GET http://localhost:5000/cariSiswa
Authorization: Bearer 
Content-Type: application/json

{
    "id":"2"
}

# 2
###
POST   http://localhost:5000/users
Content-Type: application/json

{
    "name":"Indra",
    "email":"halo",
    "password":"123",
    "confPassword":"123"
}

# 3
###
POST   http://localhost:5000/login
Content-Type: application/json

{
    "email":"13186",
    "password":"0069348822"
}

# 4
###
GET http://localhost:5000/token

# 5
###
DELETE http://localhost:5000/logout

# 6
###
DELETE http://localhost:5000/admin/logout


# 7
###
POST  http://localhost:5000/LoginAdmin
Content-Type: application/json

{
    "email":"hal0",
    "password":"13"
}

# 8
###
GET http://localhost:5000/tokenAdmin

# 9
###
POST http://localhost:5000/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ0NCwibmFtZSI6IkluZHJhIiwiZW1haWwiOiJoYWxvIiwiaWF0IjoxNjc4MzMzMDQxLCJleHAiOjE2NzgzMzMwNjF9.9rY6yednQ0GSq2WiF959WaVBb78FNuLeaqA1aoTuJwc

# 10
###
GET http://localhost:5000/hapusSiswa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ0NCwibmFtZSI6IkluZHJhIiwiZW1haWwiOiJoYWxvIiwiaWF0IjoxNjc4MzMzMDQxLCJleHAiOjE2NzgzMzMwNjF9.9rY6yednQ0GSq2WiF959WaVBb78FNuLeaqA1aoTuJwc
Content-Type: application/json

{
    "nis":"123"
}

# 11
###
GET http://localhost:5000/hapusPilihan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ0NCwibmFtZSI6IkluZHJhIiwiZW1haWwiOiJoYWxvIiwiaWF0IjoxNjc4MzM1Mzc2LCJleHAiOjE2NzgzMzUzOTZ9.Ryu6nsOX9sBfNgczZUW4wCYIj1W6j0yH5G0VE6XtMAI
Content-Type: application/json

{
    "nis":"13181"
}

# 11
###
POST http://localhost:5000/cariSiswa1
Content-Type: application/json

{
    "nis":"k"
}
###
POST http://localhost:5000/sisa

###
GET http://localhost:5000/mapel